name: 'consumable-code-news-api'
description: 'Retrofit has been Handled !! || Consumable code for request API (News API)'
author: 'Muhammad Faisal Amir'
inputs:
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}